---
- hosts: all
  name: Configure EC2
  become: true
  
  tasks:
    - name: Update and upgrade
      apt:
        update_cache: yes
        upgrade: dist
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Install Nginx
      apt:
        name: nginx
        state: present
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Enable and start Nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Install UFW
      apt:
        name: ufw
        state: present
      environment:
        DEBIAN_FRONTEND: noninteractive

    - name: Allow HTTP through UFW
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: Allow HTTPS through UFW
      community.general.ufw:
        rule: allow
        port: '443'
        proto: tcp

    - name: Allow SSH through UFW
      community.general.ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: Set logging
      community.general.ufw:
        logging: 'on'

    - name: Enable UFW
      community.general.ufw:
        state: enabled

    - name: Add alias to .bashrc
      lineinfile:
        path: /home/{{ ansible_user }}/.bashrc
        line: "alias c=clear"
        create: yes
