---
- name: Configure EC2 instance
  hosts: all
  become: yes
  
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Enable and start Nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Install UFW
      apt:
        name: ufw
        state: present

    - name: Allow HTTP through UFW
      ufw:
        rule: allow
        port: '80'

    - name: Allow HTTPS through UFW
      ufw:
        rule: allow
        port: '443'

    - name: Allow SSH through UFW
      ufw:
        rule: allow
        port: '22'

    - name: Enable UFW
      ufw:
        state: enabled

    - name: Add alias to .bashrc
      lineinfile:
        path: /home/admin/.bashrc
        line: "alias c=clear"
        create: yes
